apiVersion: v1
kind: Service
metadata:
  name: phpmyadmin
  annotations:
    metallb.universe.tf/allow-shared-ip: "ft_services"
spec:
  type: LoadBalancer
  selector:
    app: phpmyadmin
  ports:
    - name: phpmyadmin
      port: 5000
---
apiVersion: apps/v1
kind: Deployment
metadata:
 labels:
   app: phpmyadmin # このラベルは全部のpodにつけられる
 name: phpmyadmin  # deploymentの名前
spec:  # podの概要
 replicas: 1
 selector:
   matchLabels:
     app: phpmyadmin
 template: # podのtemplate
   metadata:
     labels:
       app: phpmyadmin
   spec:
     containers:
     - image: mypma
       imagePullPolicy: Never
       name: phpmyadmin
       livenessProbe:
         exec:
           command: ["sh", "./livenessprobe.sh"]
         initialDelaySeconds: 30 # コンテナ起動してから確認を開始するまで
         timeoutSeconds: 10
         periodSeconds: 30
       ports:
       - containerPort: 5000
