apiVersion: v1
kind: Service
metadata:
 name: wordpress
 annotations:
   metallb.universe.tf/allow-shared-ip: "ft_services"
spec:
 type: LoadBalancer
 selector: 
   app: wordpress
 ports:
   - name: wordpress
     port: 5050
---
apiVersion: apps/v1
kind: Deployment
metadata:
 labels:
   app: wordpres
 name: wordpress
spec:
 replicas: 1
 selector:
   matchLabels:
     app: wordpress
 template:
   metadata:
     labels:
       app: wordpress
   spec:
     containers:
     - image: mywordpress
       imagePullPolicy: Never
       name: wordpress
       livenessProbe:
         exec:
           command: ["sh", "./livenessprobe.sh"]
         initialDelaySeconds: 30 # コンテナ起動してから確認を開始するまで
         timeoutSeconds: 10
         periodSeconds: 30
       ports:
       - containerPort: 5050
